//! Panel implementations — each file is a self-contained widget.

pub mod browse_results;
pub mod cockpit;
pub mod codec_hub;
pub mod eagle;
pub mod exit_confirm;
pub mod file_browser;
pub mod firmware;
pub mod help;
pub mod info_text;
pub mod input;
pub mod lossless_prompt;
pub mod main_hub;
pub mod menu;
pub mod mode_panel;
pub mod output;
pub mod peers;
pub mod portal;
pub mod preflight;
pub mod resume;
pub mod root_warn;
pub mod settings;
pub mod settings_help;
pub mod splash;
pub mod syscheck;
pub mod tutorial;
pub mod visualization;
pub mod wizard;
