/*
 * LML Lossless EEG Codec — C API
 *
 * Generated by cbindgen. Do not edit manually.
 * Source: lamquant-core/src/ffi.rs
 *
 * Usage:
 *   #include "lml.h"
 *   int16_t signal[21 * 2500];
 *   uint8_t buf[200000];
 *   uint32_t out_len;
 *   int rc = lml_compress(signal, 21, 2500, 0, buf, sizeof(buf), &out_len);
 *   if (rc != LML_OK) { fprintf(stderr, "%s\n", lml_error_string(rc)); }
 */


#ifndef LML_H
#define LML_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Streaming CRC-32: feed multiple slices without concatenating.
 *
 * Usage:
 *     let mut state = CRC32_INIT;
 *     state = crc32_update(state, &slice_a);
 *     state = crc32_update(state, &slice_b);
 *     let crc = state ^ CRC32_INIT;
 */
#define CRC32_INIT 4294967295

/**
 * Fixed footer size in bytes. Pinned across the lifetime of `LMLFOOT1`;
 * any future format change bumps the magic suffix.
 */
#define FOOTER_SIZE 32

/**
 * Bytes per offset table entry.
 */
#define ENTRY_SIZE 16

/**
 * Maximum op_log lines retained in AppState. Older lines drop on push.
 * Keeps StateSnapshot serialization bounded — large logs go to the
 * OutputPanel (TUI) or could be streamed via a separate channel.
 */
#define OP_LOG_CAP 200

/**
 * Error codes returned by all FFI functions.
 */
#define LML_OK 0

#define LML_ERROR_INVALID_INPUT -1

#define LML_ERROR_CORRUPT_DATA -2

#define LML_ERROR_BUFFER_TOO_SMALL -3

#define LML_ERROR_UNSUPPORTED_VERSION -4

#define LML_ERROR_IO -5













/**
 * Version string.
 */
const char *lml_version(void);

/**
 * Compress interleaved i64 signal → LML packet bytes.
 *
 * signal: pointer to [n_channels * n_samples] i64 values (channel-major)
 * out_buf: pre-allocated output buffer
 * out_len: on success, receives actual bytes written
 *
 * Returns LML_OK or negative error code.
 */
int32_t lml_compress(const int64_t *signal,
                     uint32_t n_channels,
                     uint32_t n_samples,
                     uint8_t noise_bits,
                     uint8_t *out_buf,
                     uint32_t out_cap,
                     uint32_t *out_len);

/**
 * Decompress LML packet → flat i64 signal.
 *
 * data: compressed bytes
 * signal_out: pre-allocated [n_channels * n_samples] i64 buffer
 * n_channels_out, n_samples_out: receive actual dimensions
 *
 * Returns LML_OK or negative error code.
 */
int32_t lml_decompress(const uint8_t *data,
                       uint32_t data_len,
                       int64_t *signal_out,
                       uint32_t signal_cap,
                       uint32_t *n_channels_out,
                       uint32_t *n_samples_out);

/**
 * Get human-readable error string for an error code.
 */
const char *lml_error_string(int32_t code);

#endif  /* LML_H */
