/*
 * LML Lossless EEG Codec — C API
 *
 * Generated by cbindgen. Do not edit manually.
 * Source: lamquant-core/src/ffi.rs
 *
 * Usage:
 *   #include "lml.h"
 *   int16_t signal[21 * 2500];
 *   uint8_t buf[200000];
 *   uint32_t out_len;
 *   int rc = lml_compress(signal, 21, 2500, 0, buf, sizeof(buf), &out_len);
 *   if (rc != LML_OK) { fprintf(stderr, "%s\n", lml_error_string(rc)); }
 */


#ifndef LML_H
#define LML_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Maximum bits per packed residual. zigzag(i64::MIN) yields a u64
 * up to 2^64 - 1, which needs 64 bits. We cap at 63 because the
 * LPC residual ceiling (`golomb::MAX_Q = 2^40`) is way smaller and
 * 63 fits in a `u8` width-field with one bit reserved for a future
 * extension. Any value requiring ≥ 64 bits is rejected.
 */
#define MAX_BIT_PACK_BITS 63

/**
 * Minimum bits per packed residual. Forced to 1 even when every
 * sample is zero — the alternative is special-casing a zero-length
 * payload which adds branchy decoder code for negligible savings.
 */
#define MIN_BIT_PACK_BITS 1

#define LMQC_VERSION 1

#define HEADER_SIZE 20

#define FLAG_NAMES (1 << 0)

#define FLAG_COORDS (1 << 1)

#define PAYLOAD_FP16_LATENT 0

#define PAYLOAD_FSQ_TOKENS 1

/**
 * Upper bound on the n_symbols a caller can request the decoder to
 * produce. Bounds `Vec::with_capacity(n_symbols)` against attacker-
 * supplied size so an adversarial Python client can't force an OOM
 * abort by claiming billions of output symbols. EEG windows are
 * bounded at ~2500 samples × ~32 channels × ~4 subbands ≈ 320 K
 * max realistic n_symbols. 2^20 = 1 M is a generous defensive
 * ceiling; legitimate calls stay well below it.
 */
#define MAX_RANS_SYMBOLS (1 << 20)

/**
 * Fixed footer size in bytes. Pinned across the lifetime of `LMLFOOT1`;
 * any future format change bumps the magic suffix.
 */
#define FOOTER_SIZE 32

/**
 * Bytes per offset table entry.
 */
#define ENTRY_SIZE 16

#define ENC_VERSION 1

#define ENC_NONCE_LEN 12

#define ENC_HEADER_LEN ((8 + 1) + ENC_NONCE_LEN)

#define KEY_LEN 32

#define HMAC_TAG_LEN 32

/**
 * Magic + version + params length. Used by callers to size buffers.
 */
#define LmcryptHeader_SIZE 32

/**
 * Maximum op_log lines retained in AppState. Older lines drop on push.
 * Keeps StateSnapshot serialization bounded — large logs go to the
 * OutputPanel (TUI) or could be streamed via a separate channel.
 */
#define OP_LOG_CAP 200

/**
 * Error codes returned by all FFI functions.
 */
#define LML_OK 0

#define LML_ERROR_INVALID_INPUT -1

#define LML_ERROR_CORRUPT_DATA -2

#define LML_ERROR_BUFFER_TOO_SMALL -3

#define LML_ERROR_UNSUPPORTED_VERSION -4

#define LML_ERROR_IO -5













/**
 * Version string.
 */
const char *lml_version(void);

/**
 * Compress interleaved i64 signal → LML packet bytes.
 *
 * signal: pointer to [n_channels * n_samples] i64 values (channel-major)
 * out_buf: pre-allocated output buffer
 * out_len: on success, receives actual bytes written
 *
 * Returns LML_OK or negative error code.
 */
int32_t lml_compress(const int64_t *signal,
                     uint32_t n_channels,
                     uint32_t n_samples,
                     uint8_t noise_bits,
                     uint8_t *out_buf,
                     uint32_t out_cap,
                     uint32_t *out_len);

/**
 * Decompress LML packet → flat i64 signal.
 *
 * data: compressed bytes
 * signal_out: pre-allocated [n_channels * n_samples] i64 buffer
 * n_channels_out, n_samples_out: receive actual dimensions
 *
 * Returns LML_OK or negative error code.
 */
int32_t lml_decompress(const uint8_t *data,
                       uint32_t data_len,
                       int64_t *signal_out,
                       uint32_t signal_cap,
                       uint32_t *n_channels_out,
                       uint32_t *n_samples_out);

/**
 * Get human-readable error string for an error code.
 */
const char *lml_error_string(int32_t code);

#endif  /* LML_H */
