#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "../firmware_export/focal_net_weights.h"
#include "../neural/focal_modulation.h"
#include "hybrid_entropy.h"

/*
 * LamQuant Gen 7 — Hybrid Entropy Encoder (Stage 4)
 * ==================================================
 * Golden path: FSQ quantization → rANS entropy coding
 * Lightning path: Golomb-Rice on lifting tile residuals
 *
 * Gen 7 changes:
 *   - FSQ levels configurable (exported from training, default L=16)
 *   - rANS frequency table imported from focal_net_weights.h
 *   - Latent temporal dim is T/8 = 312 (stride-8 encoder)
 *   - FSQ thresholds computed from exported vmin/vmax range
 *
 * Output: 240-byte BLE packet with sync header + compressed payload.
 * 32-bit rANS state (no 64-bit emulation on RV32).
 * ZERO float.
 */

#define BUFFER_SIZE_BYTES 240
#define RANS_L (1u << 15)

/* Sync header: "LAMQ" */
#define SYNC_BYTE_0 0x51  /* 'Q' */
#define SYNC_BYTE_1 0x4D  /* 'M' */
#define SYNC_BYTE_2 0x41  /* 'A' */
#define SYNC_BYTE_3 0x4C  /* 'L' */

#define MODE_GOLDEN    0x00
#define MODE_LIGHTNING 0x01

static uint8_t  bit_buffer[BUFFER_SIZE_BYTES] __attribute__((section(".scratch_x.bit_buffer")));
static uint32_t buf_byte_idx;
static uint32_t buf_bit_idx;
static uint32_t rans_state;

/*
 * FSQ + rANS parameters — imported from focal_net_weights.h
 *
 * These are generated by export_firmware.py from the trained model's
 * actual latent distribution:
 *
 *   FSQ_NUM_LEVELS   — number of quantization bins (e.g., 16)
 *   RANS_TOTAL_FREQ  — sum of frequency table (power of 2, e.g., 4096)
 *   fsq_rans_freq[]  — per-symbol frequency counts, length FSQ_NUM_LEVELS
 *   fsq_rans_start[] — cumulative frequencies, length FSQ_NUM_LEVELS
 *   fsq_vmin_q31     — minimum latent value in Q31
 *   fsq_vmax_q31     — maximum latent value in Q31
 *
 * If these aren't in the header yet (first build), fall back to defaults.
 */
#ifndef FSQ_NUM_LEVELS
#define FSQ_NUM_LEVELS 16
#endif

#ifndef RANS_TOTAL_FREQ
#define RANS_TOTAL_FREQ 4096
#endif

/* ================================================================
 * Bit packing
 * ================================================================ */

static inline void push_bits(uint32_t bits, uint32_t num_bits) {
    for (uint32_t i = 0; i < num_bits; i++) {
        if (buf_byte_idx >= BUFFER_SIZE_BYTES) return;
        bit_buffer[buf_byte_idx] |= ((bits >> i) & 1) << buf_bit_idx;
        buf_bit_idx++;
        if (buf_bit_idx == 8) {
            buf_bit_idx = 0;
            buf_byte_idx++;
        }
    }
}

static inline void push_byte(uint8_t b) {
    if (buf_byte_idx < BUFFER_SIZE_BYTES) {
        bit_buffer[buf_byte_idx] = b;
        buf_byte_idx++;
        buf_bit_idx = 0;
    }
}

/* ================================================================
 * rANS encoder
 * ================================================================ */

static void rans_encode_symbol(uint32_t sym) {
    if (sym >= FSQ_NUM_LEVELS) sym = FSQ_NUM_LEVELS / 2;  /* Safety: map to middle bin */

    uint32_t freq  = fsq_rans_freq[sym];
    uint32_t start = fsq_rans_start[sym];

    /* Branchless renormalization: deterministic timing, no pipeline stalls.
     * Flush up to 2 bytes (sufficient for 16-bit precision rANS). */
    uint32_t x_max = ((RANS_L / RANS_TOTAL_FREQ) * freq) | 1u;  /* |1 avoids zero without branch */
    uint32_t bound = x_max << 16;

    /* Byte 1: conditionally flush via arithmetic mask */
    uint32_t need_flush1 = (uint32_t)(-(int32_t)(rans_state >= bound));  /* 0xFFFFFFFF or 0 */
    push_bits(rans_state & (need_flush1 & 0xFF), (need_flush1 & 8));
    rans_state = (rans_state >> (need_flush1 & 8)) | (rans_state & ~need_flush1);

    /* Byte 2: may need a second flush */
    uint32_t need_flush2 = (uint32_t)(-(int32_t)(rans_state >= bound));
    push_bits(rans_state & (need_flush2 & 0xFF), (need_flush2 & 8));
    rans_state = (rans_state >> (need_flush2 & 8)) | (rans_state & ~need_flush2);

    /* Encode */
    rans_state = ((rans_state / freq) * RANS_TOTAL_FREQ) + start + (rans_state % freq);
}

static void rans_flush_state(void) {
    push_bits(rans_state & 0xFF, 8);
    push_bits((rans_state >> 8) & 0xFF, 8);
    push_bits((rans_state >> 16) & 0xFF, 8);
    push_bits((rans_state >> 24) & 0xFF, 8);
}

/* ================================================================
 * FSQ quantization (uniform scalar, integer only)
 * ================================================================
 *
 * Maps a Q31 latent value to a bin index [0, FSQ_NUM_LEVELS-1].
 *
 * bin = clamp((val - vmin) * FSQ_NUM_LEVELS / (vmax - vmin), 0, L-1)
 *
 * To avoid division at runtime, we precompute the inverse range
 * as a Q31 fixed-point multiplier at export time:
 *   fsq_inv_range_q31 = (FSQ_NUM_LEVELS * 2^31) / (vmax - vmin)
 *
 * Then: bin = clamp((val - vmin) * fsq_inv_range_q31 >> 31, 0, L-1)
 */

static inline uint32_t fsq_quantize(int32_t val) {
    /* Shift to zero-based: val - vmin */
    int32_t shifted = val - fsq_vmin_q31;
    if (shifted < 0) shifted = 0;

    /* Multiply by precomputed inverse range, result in high 32 bits */
    /* We want: shifted * FSQ_NUM_LEVELS / range
     * Using: shifted * fsq_inv_range_q31 >> 31 */
    int64_t product = (int64_t)shifted * (int64_t)fsq_inv_range_q31;
    int32_t bin = (int32_t)(product >> 31);

    /* Clamp to valid range */
    if (bin < 0) bin = 0;
    if (bin >= FSQ_NUM_LEVELS) bin = FSQ_NUM_LEVELS - 1;

    return (uint32_t)bin;
}

/* ================================================================
 * Golomb-Rice encoder (lightning path)
 * ================================================================ */

static void rice_encode(int32_t residual, uint32_t k) {
    /* Zigzag: 0→0, -1→1, 1→2, -2→3, ... */
    uint32_t mapped = (residual >= 0)
        ? (uint32_t)(residual << 1)
        : (uint32_t)((-residual << 1) - 1);

    uint32_t q = mapped >> k;
    uint32_t rem = mapped & ((1u << k) - 1);

    for (uint32_t i = 0; i < q && buf_byte_idx < BUFFER_SIZE_BYTES - 2; i++) {
        push_bits(1, 1);
    }
    push_bits(0, 1);
    push_bits(rem, k);
}

/* ================================================================
 * Golden path: FSQ + rANS on TNN latent
 * ================================================================ */

/* get_latent_output() and get_latent_temporal_length() come from focal_modulation.h */
extern int32_t lifting_tile_2d[6][32];

/* ================================================================
 * Gen 7.1: Detail subband Golomb-Rice encoder
 * ================================================================
 *
 * Encodes sparse detail coefficients (after thresholding) using
 * Golomb-Rice with run-length encoding of zero positions.
 *
 * Encoding format per subband:
 *   1. Subband header: adaptive k parameter (4 bits)
 *   2. For each coefficient:
 *      - If zero: emit run-length (Golomb-Rice encoded run of zeros)
 *      - If nonzero: emit 0-length run, then Golomb-Rice encoded value
 *
 * The run-length scheme exploits the sparsity after thresholding:
 * if 80% of coefficients are zero, most of the bitstream is
 * short run-length codes rather than full coefficient values.
 */

/* Subband lengths */
#define SUBBAND_L3_DETAIL_LEN 312
#define SUBBAND_L2_DETAIL_LEN 625
#define SUBBAND_L1_DETAIL_LEN 1250
#define DETAIL_NUM_CHANNELS   21

static void rice_encode_sparse_subband(
    const int32_t* coeffs, int len, uint32_t k_init
) {
    /* Emit k parameter (4 bits) */
    push_bits(k_init & 0x0F, 4);

    uint32_t k = k_init;
    uint32_t run = 0;               /* Current run of zeros */
    uint32_t abs_accum = 0;
    uint32_t sample_count = 0;

    for (int i = 0; i < len && buf_byte_idx < BUFFER_SIZE_BYTES - 4; i++) {
        if (coeffs[i] == 0) {
            run++;
            continue;
        }

        /* Emit the run of zeros (Golomb-Rice encoded) */
        {
            uint32_t q = run >> 3;  /* Run k=3 for run-lengths */
            uint32_t rem = run & 0x07;
            /* Unary: q ones + stop zero */
            for (uint32_t j = 0; j < q && buf_byte_idx < BUFFER_SIZE_BYTES - 2; j++)
                push_bits(1, 1);
            push_bits(0, 1);
            push_bits(rem, 3);
        }
        run = 0;

        /* Emit the non-zero coefficient (Golomb-Rice with adaptive k) */
        rice_encode(coeffs[i], k);

        /* Update adaptive k */
        int32_t v = coeffs[i];
        uint32_t abs_val = (v >= 0) ? (uint32_t)v : (uint32_t)(-v);
        abs_accum += abs_val;
        sample_count++;

        if (sample_count >= 16) {
            uint32_t mean_abs = abs_accum / sample_count;
            uint32_t new_k = 0;
            uint32_t m = mean_abs;
            while (m > 1) { m >>= 1; new_k++; }
            if (new_k < 1) new_k = 1;
            if (new_k > 8) new_k = 8;
            k = new_k;
            abs_accum = 0;
            sample_count = 0;
        }
    }

    /* Flush trailing run of zeros (if any) */
    if (run > 0 && buf_byte_idx < BUFFER_SIZE_BYTES - 2) {
        uint32_t q = run >> 3;
        uint32_t rem = run & 0x07;
        for (uint32_t j = 0; j < q && buf_byte_idx < BUFFER_SIZE_BYTES - 2; j++)
            push_bits(1, 1);
        push_bits(0, 1);
        push_bits(rem, 3);
    }
}

/*
 * Encode all detail subbands according to quality mode.
 *
 * @param l3_detail  [21][312] — thresholded L3 detail
 * @param l2_detail  [21][625] — thresholded L2 detail (NULL if not included)
 * @param l1_detail  [21][1250] — thresholded L1 detail (NULL if not included)
 * @param subband_mask  bitmask: bit0=L3, bit1=L2, bit2=L1
 */
void encode_detail_subbands(
    const int32_t l3_detail[][SUBBAND_L3_DETAIL_LEN],
    const int32_t l2_detail[][SUBBAND_L2_DETAIL_LEN],
    const int32_t l1_detail[][SUBBAND_L1_DETAIL_LEN],
    uint8_t subband_mask
) {
    /* Emit subband mask (1 byte) */
    push_byte(subband_mask);

    /* L3 detail (always included if mask bit 0 set) */
    if (subband_mask & 0x01) {
        for (int ch = 0; ch < DETAIL_NUM_CHANNELS && buf_byte_idx < BUFFER_SIZE_BYTES - 8; ch++) {
            rice_encode_sparse_subband(l3_detail[ch], SUBBAND_L3_DETAIL_LEN, 4);
        }
    }

    /* L2 detail */
    if ((subband_mask & 0x02) && l2_detail != NULL) {
        for (int ch = 0; ch < DETAIL_NUM_CHANNELS && buf_byte_idx < BUFFER_SIZE_BYTES - 8; ch++) {
            rice_encode_sparse_subband(l2_detail[ch], SUBBAND_L2_DETAIL_LEN, 3);
        }
    }

    /* L1 detail */
    if ((subband_mask & 0x04) && l1_detail != NULL) {
        for (int ch = 0; ch < DETAIL_NUM_CHANNELS && buf_byte_idx < BUFFER_SIZE_BYTES - 8; ch++) {
            rice_encode_sparse_subband(l1_detail[ch], SUBBAND_L1_DETAIL_LEN, 3);
        }
    }
}

static void encode_golden_payload(const int32_t latent[][79], int T_latent) {
    rans_state = RANS_L;

    /* Encode in reverse (rANS is LIFO) */
    for (int t = T_latent - 1; t >= 0 && buf_byte_idx < BUFFER_SIZE_BYTES - 8; t--) {
        for (int d = 31; d >= 0; d--) {
            uint32_t sym = fsq_quantize(latent[d][t]);
            rans_encode_symbol(sym);
        }
    }

    rans_flush_state();
}

/* ================================================================
 * Lightning path: Golomb-Rice on lifting tile
 * Adaptive k: running estimate of mean |residual|, updated every 32 samples.
 * Improves Lightning CR by 5-15% vs fixed k=4.
 * ================================================================ */

static uint32_t rice_k_adaptive = 4;      /* Current adaptive k parameter */
static uint32_t rice_abs_accum = 0;        /* Running sum of |residual| */
static uint32_t rice_sample_count = 0;     /* Samples since last k update */

static void rice_update_k(int32_t residual) {
    uint32_t abs_val = (residual >= 0) ? (uint32_t)residual : (uint32_t)(-residual);
    rice_abs_accum += abs_val;
    rice_sample_count++;

    if (rice_sample_count >= 32) {
        /* Estimate optimal k = floor(log2(mean_abs)) */
        uint32_t mean_abs = rice_abs_accum / rice_sample_count;
        uint32_t k = 0;
        uint32_t m = mean_abs;
        while (m > 1) { m >>= 1; k++; }
        /* Clamp k to reasonable range [1, 8] */
        if (k < 1) k = 1;
        if (k > 8) k = 8;
        rice_k_adaptive = k;
        rice_abs_accum = 0;
        rice_sample_count = 0;
    }
}

static void encode_lightning_payload(void) {
    /* Reset adaptive k at start of each frame */
    rice_k_adaptive = 4;
    rice_abs_accum = 0;
    rice_sample_count = 0;

    for (int ch = 0; ch < 6; ch++) {
        for (int t = 0; t < 32; t++) {
            if (buf_byte_idx >= BUFFER_SIZE_BYTES - 4) return;
            rice_update_k(lifting_tile_2d[ch][t]);
            rice_encode(lifting_tile_2d[ch][t], rice_k_adaptive);
        }
    }
}

/* ================================================================
 * Public API — called by scheduler.c
 * ================================================================ */

void run_hybrid_entropy_encoder(bool degraded) {
    memset(bit_buffer, 0, BUFFER_SIZE_BYTES);
    buf_byte_idx = 0;
    buf_bit_idx = 0;

    /* Sync header (4 bytes) */
    push_byte(SYNC_BYTE_0);
    push_byte(SYNC_BYTE_1);
    push_byte(SYNC_BYTE_2);
    push_byte(SYNC_BYTE_3);

    /* Mode flag (1 byte): includes FSQ level count for receiver */
    push_byte(degraded ? MODE_LIGHTNING : MODE_GOLDEN);

    /* FSQ level count (1 byte): receiver needs this to decode */
    if (!degraded) {
        push_byte((uint8_t)FSQ_NUM_LEVELS);
    }

    if (!degraded) {
        int T_lat = get_latent_temporal_length();
        const int32_t (*latent)[79] = (const int32_t (*)[79])get_latent_output();
        encode_golden_payload(latent, T_lat);
    } else {
        encode_lightning_payload();
    }
}

const uint8_t* get_entropy_buffer(void) {
    return bit_buffer;
}

uint32_t get_entropy_buffer_used_bytes(void) {
    return buf_byte_idx + (buf_bit_idx > 0 ? 1 : 0);
}
