/*
 * LamQuant Gen 7 — dLIF SNN Activity Detector (firmware)
 * ======================================================
 * Integer-only dLIF implementation for Hazard3 RV32.
 *
 * Pipeline:
 *   1. Delta encoding: 21ch Q31 → binary spikes (threshold crossing)
 *   2. Ternary spatial conv: 21→64, k=5 (XNOR+cpop ready)
 *   3. dLIF hidden: 64 neurons, 2 dendrites, shift-based decay
 *   4. dLIF readout: 8 neurons → activity_map[8][312]
 *
 * Memory budget:
 *   Weights:  ~5 KB in SRAM5 (from snn_weights.h)
 *   State:    ~1 KB in SRAM6 (neurons + activity map)
 *   Scratch:  ~0.5 KB stack (conv output buffer)
 *
 * ZERO float. ZERO division (shift-based decay).
 * ~180K integer ops per 10-second window.
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "snn.h"
#include "../core/math_utils.h"

/* Import trained weights — generated by train_dlif.py --export */
#ifdef SNN_USE_TRAINED_WEIGHTS
#include "../firmware_export/snn_weights.h"
#else
/* Placeholder defaults for compilation before training */
#define SNN_DELTA_THRESHOLD_Q31  107374182   /* ~0.05 in Q31 */
#define SNN_SOMA_DECAY_SHIFT     2           /* alpha = 0.75 */
#define SNN_DEND_DECAY_SHIFT     4           /* alpha = 0.9375 */
#define SNN_HIDDEN_NEURONS       64
#define SNN_READOUT_NEURONS      8
#endif

/* Ternary weight LUT: 2-bit -> {0, +1, -1, 0}
 * Only used when SNN_USE_TRAINED_WEIGHTS is defined. */
#ifdef SNN_USE_TRAINED_WEIGHTS
static const int32_t TERNARY_LUT[4] = {0, 1, -1, 0};
#endif

/* ================================================================
 * State in SRAM6
 * ================================================================ */

static dlif_neuron_t hidden_neurons[SNN_HIDDEN_DIM]
    __attribute__((section(".snn_state_sram6")));

static dlif_neuron_t readout_neurons[SNN_READOUT_DIM]
    __attribute__((section(".snn_state_sram6")));

static uint8_t activity_map[SNN_READOUT_DIM][SNN_T_LATENT]
    __attribute__((section(".snn_state_sram6")));

/* Previous sample for delta encoding */
static int32_t prev_sample[SNN_INPUT_CH]
    __attribute__((section(".snn_state_sram6")));

/* Scratch buffer for conv output (on stack or SRAM6) */
static int32_t conv_output[SNN_HIDDEN_DIM];

/* Per-group spike accumulators for stride-8 pooling */
static uint8_t spike_accum[SNN_READOUT_DIM];

/* Runtime-tunable sensitivity. Defaults match SNN_K_GLOBAL/SNN_K_LOCAL. */
static snn_sensitivity_t g_sensitivity = SNN_SENSITIVITY_MEDIUM;
static uint8_t g_k_local  = SNN_K_LOCAL;     /* per-group spike rate threshold */
static uint8_t g_k_global = SNN_K_GLOBAL;    /* (kept for parity with research) */

/* ================================================================
 * Initialization
 * ================================================================ */

void snn_init(void) {
    memset(hidden_neurons, 0, sizeof(hidden_neurons));
    memset(readout_neurons, 0, sizeof(readout_neurons));
    memset(activity_map, 0, sizeof(activity_map));
    memset(prev_sample, 0, sizeof(prev_sample));
    memset(spike_accum, 0, sizeof(spike_accum));

    /* Set initial thresholds */
    for (int i = 0; i < SNN_HIDDEN_DIM; i++) {
#ifdef SNN_USE_TRAINED_WEIGHTS
        hidden_neurons[i].V_threshold = snn_hidden_vthresh_q31[i];
#else
        hidden_neurons[i].V_threshold = (int32_t)(0x40000000); /* 0.5 Q31 */
#endif
    }
    for (int i = 0; i < SNN_READOUT_DIM; i++) {
#ifdef SNN_USE_TRAINED_WEIGHTS
        readout_neurons[i].V_threshold = snn_readout_vthresh_q31[i];
#else
        readout_neurons[i].V_threshold = (int32_t)(0x40000000);
#endif
    }
}

/* ================================================================
 * Delta encoding
 * ================================================================ */

static inline bool delta_spike(int32_t current, int32_t previous) {
    int32_t diff = current - previous;
    if (diff < 0) diff = -diff;
    return diff > SNN_DELTA_THRESHOLD_Q31;
}

/* ================================================================
 * Ternary spatial convolution: 21→64, k=5
 *
 * For each output channel, convolve across input channels with
 * a 5-tap ternary kernel. Output is Q31 scaled by alpha.
 * ================================================================ */

static void snn_spatial_conv(const int32_t input_spikes[], int t,
                             const int32_t input_buf[][313]) {
#ifdef SNN_USE_TRAINED_WEIGHTS
    int weights_per_oc = SNN_INPUT_CH * SNN_CONV_KERNEL;
    int bytes_per_oc = (weights_per_oc + 3) / 4;
    int half_k = SNN_CONV_KERNEL / 2;

    for (int oc = 0; oc < SNN_HIDDEN_DIM; oc++) {
        const uint8_t *w = &snn_conv_weights[oc * bytes_per_oc];
        int32_t acc = 0;
        int w_idx = 0;

        for (int ic = 0; ic < SNN_INPUT_CH; ic++) {
            for (int ki = -half_k; ki <= half_k; ki++) {
                int ti = t + ki;
                int32_t a = (ti >= 0 && ti < 313) ? input_buf[ic][ti] : 0;

                int byte_pos = w_idx / 4;
                int bit_pos = (w_idx % 4) * 2;
                int32_t wv = TERNARY_LUT[(w[byte_pos] >> bit_pos) & 0x03];

                acc += (a >> 16) * wv;  /* Q15 * ternary */
                w_idx++;
            }
        }

        conv_output[oc] = mul_q31(acc, snn_conv_alphas_q31[oc]);
    }
#else
    /* Placeholder: pass through first 64 spike indicators */
    (void)t;
    (void)input_buf;
    for (int oc = 0; oc < SNN_HIDDEN_DIM; oc++) {
        conv_output[oc] = (oc < SNN_INPUT_CH && input_spikes[oc])
            ? (int32_t)0x20000000 : 0;
    }
#endif
}

/* ================================================================
 * dLIF neuron step (shift-based, branchless where possible)
 * ================================================================ */

static inline bool dlif_step(dlif_neuron_t *n, int32_t i_syn0, int32_t i_syn1,
                              int soma_shift, int dend_shift) {
    /* Dendritic integration: V_d += (I_syn - V_d) >> dend_shift */
    n->V_dendrite[0] += (i_syn0 - n->V_dendrite[0]) >> dend_shift;
    n->V_dendrite[1] += (i_syn1 - n->V_dendrite[1]) >> dend_shift;

    /* Sum dendrites into soma current */
    int32_t i_total = n->V_dendrite[0] + n->V_dendrite[1];

    /* Somatic integration: V_s += (I_total - V_s) >> soma_shift */
    n->V_soma += (i_total - n->V_soma) >> soma_shift;

    /* Adaptive threshold: EMA of |V_soma| */
    int32_t abs_v = n->V_soma >= 0 ? n->V_soma : -n->V_soma;
    n->ema_noise += (abs_v - n->ema_noise) >> 7;  /* EMA_DECAY ~0.99 via >>7 */

    /* Check threshold */
    bool spike = n->V_soma > n->V_threshold;

    /* Reset on spike (subtract threshold) */
    if (spike) {
        n->V_soma -= n->V_threshold;
    }

    return spike;
}

/* ================================================================
 * Hidden layer: 64 neurons with dendritic weights
 * ================================================================ */

static void snn_hidden_step(int32_t hidden_spikes[]) {
    for (int i = 0; i < SNN_HIDDEN_DIM; i++) {
        /* Compute dendritic synaptic currents */
        int32_t i_syn0 = 0;
        int32_t i_syn1 = 0;

#ifdef SNN_USE_TRAINED_WEIGHTS
        for (int j = 0; j < SNN_HIDDEN_DIM; j++) {
            int32_t cv = conv_output[j];
            i_syn0 += mul_q31(cv, snn_hidden_dend0_weights_q31[i][j]);
            i_syn1 += mul_q31(cv, snn_hidden_dend1_weights_q31[i][j]);
        }
#else
        i_syn0 = conv_output[i];
        i_syn1 = conv_output[i < SNN_HIDDEN_DIM - 1 ? i + 1 : 0];
#endif

        bool spike = dlif_step(&hidden_neurons[i], i_syn0, i_syn1,
                               SNN_SOMA_DECAY_SHIFT, SNN_DEND_DECAY_SHIFT);
        hidden_spikes[i] = spike ? (int32_t)0x40000000 : 0;

        /* Update adaptive threshold */
#ifdef SNN_USE_TRAINED_WEIGHTS
        hidden_neurons[i].V_threshold = snn_hidden_vthresh_q31[i]
            + mul_q31(snn_hidden_adapt_alpha_q31[i], hidden_neurons[i].ema_noise);
#endif
    }
}

/* ================================================================
 * Readout layer: 8 neurons → activity classification
 * ================================================================ */

static void snn_readout_step(const int32_t hidden_spikes[]) {
    for (int g = 0; g < SNN_READOUT_DIM; g++) {
        int32_t i_syn0 = 0;
        int32_t i_syn1 = 0;

#ifdef SNN_USE_TRAINED_WEIGHTS
        for (int j = 0; j < SNN_HIDDEN_DIM; j++) {
            int32_t hs = hidden_spikes[j];
            i_syn0 += mul_q31(hs, snn_readout_dend0_weights_q31[g][j]);
            i_syn1 += mul_q31(hs, snn_readout_dend1_weights_q31[g][j]);
        }
#else
        /* Placeholder: accumulate from spatial group */
        for (int j = g * 8; j < (g + 1) * 8 && j < SNN_HIDDEN_DIM; j++) {
            i_syn0 += hidden_spikes[j];
        }
#endif

        bool spike = dlif_step(&readout_neurons[g], i_syn0, i_syn1,
                               SNN_SOMA_DECAY_SHIFT, SNN_DEND_DECAY_SHIFT);

        if (spike) {
            spike_accum[g]++;
        }

#ifdef SNN_USE_TRAINED_WEIGHTS
        readout_neurons[g].V_threshold = snn_readout_vthresh_q31[g]
            + mul_q31(snn_readout_adapt_alpha_q31[g], readout_neurons[g].ema_noise);
#endif
    }
}

/* ================================================================
 * Full SNN inference
 * ================================================================ */

void snn_inference(const int32_t input[][313], int T) {
    int32_t input_spikes[SNN_INPUT_CH];
    int32_t hidden_spikes[SNN_HIDDEN_DIM];
    int t_latent_idx = 0;

    /* Reset state for new window */
    for (int i = 0; i < SNN_HIDDEN_DIM; i++) {
        hidden_neurons[i].V_soma = 0;
        hidden_neurons[i].V_dendrite[0] = 0;
        hidden_neurons[i].V_dendrite[1] = 0;
    }
    for (int i = 0; i < SNN_READOUT_DIM; i++) {
        readout_neurons[i].V_soma = 0;
        readout_neurons[i].V_dendrite[0] = 0;
        readout_neurons[i].V_dendrite[1] = 0;
        spike_accum[i] = 0;
    }
    memset(prev_sample, 0, sizeof(prev_sample));

    for (int t = 0; t < T; t++) {
        /* Delta encoding */
        for (int ch = 0; ch < SNN_INPUT_CH; ch++) {
            input_spikes[ch] = delta_spike(input[ch][t], prev_sample[ch]) ? 1 : 0;
            prev_sample[ch] = input[ch][t];
        }

        /* Ternary spatial convolution */
        snn_spatial_conv(input_spikes, t, input);

        /* dLIF hidden layer */
        snn_hidden_step(hidden_spikes);

        /* dLIF readout layer */
        snn_readout_step(hidden_spikes);

        /* Stride-8 pooling: every 8 samples, write activity map */
        if ((t & 7) == 7 && t_latent_idx < SNN_T_LATENT) {
            for (int g = 0; g < SNN_READOUT_DIM; g++) {
                /* Classify based on spike count in this stride window */
                if (spike_accum[g] >= g_k_local) {
                    activity_map[g][t_latent_idx] = ACTIVITY_HIGH;
                } else if (spike_accum[g] > 0) {
                    activity_map[g][t_latent_idx] = ACTIVITY_ACTIVE;
                } else {
                    activity_map[g][t_latent_idx] = ACTIVITY_QUIESCENT;
                }
                spike_accum[g] = 0;
            }
            t_latent_idx++;
        }
    }
}

/* ================================================================
 * Accessors
 * ================================================================ */

uint8_t snn_activity_sum(void) {
    uint8_t sum = 0;
    for (int g = 0; g < SNN_READOUT_DIM; g++) {
        for (int t = 0; t < SNN_T_LATENT; t++) {
            sum += activity_map[g][t];
            if (sum > 200) return sum;  /* Early exit, clearly active */
        }
    }
    return sum;
}

activity_level_t snn_get_activity(int group, int t_latent) {
    if (group < 0 || group >= SNN_READOUT_DIM) return ACTIVITY_QUIESCENT;
    if (t_latent < 0 || t_latent >= SNN_T_LATENT) return ACTIVITY_QUIESCENT;
    return (activity_level_t)activity_map[group][t_latent];
}

const uint8_t (*snn_get_activity_map(void))[SNN_T_LATENT] {
    return (const uint8_t (*)[SNN_T_LATENT])activity_map;
}

void snn_set_sensitivity(snn_sensitivity_t level) {
    if ((unsigned)level >= (unsigned)SNN_SENSITIVITY_NUM_OPTIONS) {
        level = SNN_SENSITIVITY_MEDIUM;
    }
    g_sensitivity = level;
    /* Threshold ladder: low needs more spikes, high needs fewer.
     * The K_GLOBAL knob is reserved for future use; K_LOCAL is what
     * the stride-8 classifier actually compares against. */
    switch (level) {
        case SNN_SENSITIVITY_LOW:
            g_k_local  = SNN_K_LOCAL  * 2;   /* 8 */
            g_k_global = SNN_K_GLOBAL + 8;   /* 24 */
            break;
        case SNN_SENSITIVITY_HIGH:
            g_k_local  = SNN_K_LOCAL  / 2;   /* 2 */
            g_k_global = SNN_K_GLOBAL - 6;   /* 10 */
            break;
        case SNN_SENSITIVITY_NUM_OPTIONS:
        case SNN_SENSITIVITY_MEDIUM:
        default:
            g_k_local  = SNN_K_LOCAL;        /* 4 */
            g_k_global = SNN_K_GLOBAL;       /* 16 */
            break;
    }
}

snn_sensitivity_t snn_get_sensitivity(void) {
    return g_sensitivity;
}
