/*
 * LamQuant Gen 7 — Context-Adaptive rANS Encoder
 * ================================================
 * Dual frequency tables (quiescent + event) selected per timestep
 * based on the SNN activity map.
 *
 * Key optimizations (research §4.1):
 *   - Reciprocal multiplication for division-free rANS:
 *       mulhu a3, x, recip[s]    // quotient
 *       mul   a4, a3, freq[s]    // q * f
 *       sub   a5, x, a4          // remainder
 *     3 instructions, ~4 cycles (vs 64 for DIV)
 *
 *   - Power-of-2 frequency tables where possible (shift+AND, 2 cycles)
 *   - Branchless renormalization (from Gen 6 quick win)
 *
 * Frequency tables: 2 × L_max × 4 bytes = ~162 bytes each
 * Generated from training data by export_firmware.py.
 *
 * ZERO float. 32-bit rANS state.
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "../snn/snn.h"
#include "../core/math_utils.h"
#include "fsq_adaptive.h"
#include "rans_context.h"

/* ================================================================
 * rANS parameters
 * ================================================================ */

#define RANS_L           (1u << 15)
#define RANS_TOTAL_FREQ  4096        /* 2^12 — power of 2 for shift ops */
#define MAX_SYMBOLS      32          /* Max L across all configs (Gen 7.1: L=32 clinical) */

/*
 * Dual frequency tables.
 * Table 0: quiescent — peaked distribution (most mass on central bins)
 * Table 1: event — flatter distribution (spread across bins)
 *
 * Generated by export_firmware.py from CHB-MIT training data.
 * Placeholder values below — will be overwritten by trained export.
 */

/* Frequency tables for L=2, L=3, L=5 in both contexts */
typedef struct {
    uint32_t freq[MAX_SYMBOLS];      /* Per-symbol frequency */
    uint32_t start[MAX_SYMBOLS];     /* Cumulative start */
    uint32_t recip[MAX_SYMBOLS];     /* Precomputed reciprocal: (1<<32) / freq */
    uint32_t num_symbols;
} rans_freq_table_t;

/* Context 0: quiescent, Context 1: event */
/* L=2 tables */
static rans_freq_table_t table_quiet_l2 = {
    .freq  = {3072, 1024, 0, 0, 0},
    .start = {0, 3072, 0, 0, 0},
    .recip = {0},  /* Computed at init */
    .num_symbols = 2,
};
static rans_freq_table_t table_event_l2 = {
    .freq  = {2048, 2048, 0, 0, 0},
    .start = {0, 2048, 0, 0, 0},
    .recip = {0},
    .num_symbols = 2,
};

/* L=3 tables */
static rans_freq_table_t table_quiet_l3 = {
    .freq  = {512, 3072, 512, 0, 0},
    .start = {0, 512, 3584, 0, 0},
    .recip = {0},
    .num_symbols = 3,
};
static rans_freq_table_t table_event_l3 = {
    .freq  = {1024, 2048, 1024, 0, 0},
    .start = {0, 1024, 3072, 0, 0},
    .recip = {0},
    .num_symbols = 3,
};

/* L=5 tables */
static rans_freq_table_t table_quiet_l5 = {
    .freq  = {256, 768, 2048, 768, 256},
    .start = {0, 256, 1024, 3072, 3840},
    .recip = {0},
    .num_symbols = 5,
};
static rans_freq_table_t table_event_l5 = {
    .freq  = {512, 1024, 1024, 1024, 512},
    .start = {0, 512, 1536, 2560, 3584},
    .recip = {0},
    .num_symbols = 5,
};

/*
 * L=32 tables (Gen 7.1 clinical mode).
 * Gaussian-like distribution: peaked at center, tails fall off.
 * Total frequency = 4096.
 * Placeholder values — will be overwritten by trained export.
 */
static rans_freq_table_t table_quiet_l32 = {
    .freq  = {
        8, 12, 18, 28, 42, 64, 96, 128,
        160, 192, 224, 256, 288, 304, 312, 320,
        320, 312, 304, 288, 256, 224, 192, 160,
        128, 96, 64, 42, 28, 18, 12, 8
    },
    .start = {0},  /* Computed at init */
    .recip = {0},
    .num_symbols = 32,
};
static rans_freq_table_t table_event_l32 = {
    .freq  = {
        64, 72, 80, 88, 96, 104, 112, 120,
        128, 132, 136, 140, 144, 148, 148, 148,
        148, 148, 148, 144, 140, 136, 132, 128,
        120, 112, 104, 96, 88, 80, 72, 64
    },
    .start = {0},
    .recip = {0},
    .num_symbols = 32,
};

/* Table lookup: [context][L_index] — 0=L2, 1=L3, 2=L5, 3=L32 */
static rans_freq_table_t *freq_tables[2][4] = {
    { &table_quiet_l2, &table_quiet_l3, &table_quiet_l5, &table_quiet_l32 },
    { &table_event_l2, &table_event_l3, &table_event_l5, &table_event_l32 },
};

/* ================================================================
 * Output buffer
 * ================================================================ */

#define RANS_BUF_SIZE 240
static uint8_t  rans_buffer[RANS_BUF_SIZE] __attribute__((section(".scratch_x.rans_buffer")));
static uint32_t rans_byte_idx;
static uint32_t rans_bit_idx;
static uint32_t rans_state;

static inline void rans_push_byte(uint8_t b) {
    if (rans_byte_idx < RANS_BUF_SIZE) {
        rans_buffer[rans_byte_idx++] = b;
    }
}

static inline void rans_push_bits(uint32_t bits, uint32_t n) {
    for (uint32_t i = 0; i < n; i++) {
        if (rans_byte_idx >= RANS_BUF_SIZE) return;
        rans_buffer[rans_byte_idx] |= ((bits >> i) & 1) << rans_bit_idx;
        rans_bit_idx++;
        if (rans_bit_idx == 8) {
            rans_bit_idx = 0;
            rans_byte_idx++;
        }
    }
}

/* ================================================================
 * Reciprocal computation
 * ================================================================ */

static void compute_reciprocals(rans_freq_table_t *t) {
    for (uint32_t i = 0; i < t->num_symbols; i++) {
        if (t->freq[i] > 0) {
            /* recip = ceil(2^32 / freq) */
            t->recip[i] = (uint32_t)(((uint64_t)1 << 32) / t->freq[i]);
        } else {
            t->recip[i] = 0xFFFFFFFF;
        }
    }
}

/*
 * Compute cumulative start values from frequency array.
 * Must be called before compute_reciprocals for tables
 * where .start was not hardcoded (e.g., L=32).
 */
static void compute_starts(rans_freq_table_t *t) {
    t->start[0] = 0;
    for (uint32_t i = 1; i < t->num_symbols; i++) {
        t->start[i] = t->start[i - 1] + t->freq[i - 1];
    }
}

void rans_context_init(void) {
    /* L=32 tables need cumulative starts computed */
    compute_starts(&table_quiet_l32);
    compute_starts(&table_event_l32);

    /* Compute reciprocals for all tables */
    compute_reciprocals(&table_quiet_l2);
    compute_reciprocals(&table_event_l2);
    compute_reciprocals(&table_quiet_l3);
    compute_reciprocals(&table_event_l3);
    compute_reciprocals(&table_quiet_l5);
    compute_reciprocals(&table_event_l5);
    compute_reciprocals(&table_quiet_l32);
    compute_reciprocals(&table_event_l32);
}

/* ================================================================
 * Division-free rANS encode
 * ================================================================ */

static inline void rans_encode_sym(uint32_t sym, const rans_freq_table_t *tab) {
    if (sym >= tab->num_symbols) sym = 0;  /* Safety */

    uint32_t freq  = tab->freq[sym];
    uint32_t start = tab->start[sym];

    if (freq == 0) return;  /* Skip zero-probability symbols */

    /* Branchless renormalization */
    uint32_t x_max = ((RANS_L / RANS_TOTAL_FREQ) * freq) | 1u;
    uint32_t bound = x_max << 16;

    /* Flush byte 1 */
    uint32_t need1 = (uint32_t)(-(int32_t)(rans_state >= bound));
    rans_push_bits(rans_state & (need1 & 0xFF), need1 & 8);
    rans_state = (rans_state >> (need1 & 8)) | (rans_state & ~need1);

    /* Flush byte 2 */
    uint32_t need2 = (uint32_t)(-(int32_t)(rans_state >= bound));
    rans_push_bits(rans_state & (need2 & 0xFF), need2 & 8);
    rans_state = (rans_state >> (need2 & 8)) | (rans_state & ~need2);

    /*
     * Division-free encode using precomputed reciprocal:
     *   quotient  = (rans_state * recip) >> 32  (MULHU)
     *   remainder = rans_state - quotient * freq
     *   new_state = quotient * RANS_TOTAL_FREQ + start + remainder
     */
    uint32_t recip = tab->recip[sym];
    uint32_t q = (uint32_t)(((uint64_t)rans_state * (uint64_t)recip) >> 32);
    uint32_t r = rans_state - q * freq;

    rans_state = q * RANS_TOTAL_FREQ + start + r;
}

static void rans_flush(void) {
    rans_push_bits(rans_state & 0xFF, 8);
    rans_push_bits((rans_state >> 8) & 0xFF, 8);
    rans_push_bits((rans_state >> 16) & 0xFF, 8);
    rans_push_bits((rans_state >> 24) & 0xFF, 8);
}

/* ================================================================
 * Context-adaptive encode of FSQ symbols
 * ================================================================ */

/* Sync header for v2 packet */
#define SYNC_BYTE_0 0x51  /* 'Q' */
#define SYNC_BYTE_1 0x4D  /* 'M' */
#define SYNC_BYTE_2 0x41  /* 'A' */
#define SYNC_BYTE_3 0x4C  /* 'L' */
#define MODE_GOLDEN_ADAPTIVE 0x02

/* fsq_adaptive.c accessors come from fsq_adaptive.h (included above) */

uint32_t rans_context_encode(int T_latent) {
    memset(rans_buffer, 0, RANS_BUF_SIZE);
    rans_byte_idx = 0;
    rans_bit_idx = 0;
    rans_state = RANS_L;

    /* BLE packet header v2 */
    rans_push_byte(SYNC_BYTE_0);
    rans_push_byte(SYNC_BYTE_1);
    rans_push_byte(SYNC_BYTE_2);
    rans_push_byte(SYNC_BYTE_3);
    rans_push_byte(MODE_GOLDEN_ADAPTIVE);

    /* FSQ level summary (2 bytes) */
    uint16_t level_summary = fsq_build_level_summary();
    rans_push_byte((uint8_t)(level_summary & 0xFF));
    rans_push_byte((uint8_t)(level_summary >> 8));

    /* SNN spike summary (1 byte) */
    rans_push_byte(snn_activity_sum());

    /* Encode FSQ symbols in reverse (rANS is LIFO) */
    const uint32_t *symbols = fsq_get_symbols();
    const uint8_t *level_bm = fsq_get_level_bitmap();
    uint32_t n_symbols = fsq_get_symbol_count();

    for (int i = (int)n_symbols - 1; i >= 0 && rans_byte_idx < RANS_BUF_SIZE - 8; i--) {
        /* Determine which timestep this symbol belongs to */
        int t = i / 32;
        int cfg_idx = (t < T_latent) ? level_bm[t] : 0;

        /* Determine context: quiescent=0 or event=1 */
        int context = (cfg_idx > 0) ? 1 : 0;

        /* Get the appropriate frequency table */
        const rans_freq_table_t *tab = freq_tables[context][cfg_idx];

        rans_encode_sym(symbols[i], tab);
    }

    rans_flush();

    return rans_byte_idx + (rans_bit_idx > 0 ? 1 : 0);
}

/* Accessors */
const uint8_t* rans_context_get_buffer(void) {
    return rans_buffer;
}

uint32_t rans_context_get_used_bytes(void) {
    return rans_byte_idx + (rans_bit_idx > 0 ? 1 : 0);
}
