#!/usr/bin/env bash
# tools/build_submission.sh — refresh the submission bundle.
#
# outputs/submission/ is a single drop-in directory for the IEEE
# TBioCAS portal upload:
#   - manuscript.pdf   (symlink → docs/paper/lamquant_lossless.pdf)
#   - cover_letter.md  (symlink → docs/paper/cover_letter.md)
#   - supplementary.zip (real zip, regenerated by this script)
#   - supplementary/    (loose symlink tree mirroring the zip; for
#                       browsing the source tree without unzipping)
#
# Run this script whenever docs/paper/* changes, before re-uploading.
# It pdflatex's the paper, then refreshes the zip from the symlinked
# tree (zip dereferences symlinks so reviewers get real content).
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PAPER_DIR="$REPO_ROOT/docs/paper"
SUB_DIR="$REPO_ROOT/outputs/submission"

cd "$PAPER_DIR"
echo "[1/3] pdflatex pass 1..."
pdflatex -interaction=nonstopmode lamquant_lossless.tex >/tmp/build_submission_p1.log 2>&1 || {
  echo "  pdflatex pass 1 failed; see /tmp/build_submission_p1.log"; exit 1; }
echo "[2/3] bibtex + pdflatex pass 2..."
bibtex lamquant_lossless >/tmp/build_submission_bib.log 2>&1 || true
pdflatex -interaction=nonstopmode lamquant_lossless.tex >/tmp/build_submission_p2.log 2>&1 || true
pdflatex -interaction=nonstopmode lamquant_lossless.tex >/tmp/build_submission_p3.log 2>&1 || true
PAGES=$(grep -oE 'Output written on .+ \(([0-9]+) pages' /tmp/build_submission_p3.log | grep -oE '[0-9]+ pages' | head -1)
echo "  built: $PAGES"

echo "[3/3] refreshing supplementary.zip..."
rm -f "$SUB_DIR/supplementary.zip"
(cd "$SUB_DIR" && zip -r supplementary.zip supplementary/ >/dev/null)
ZIP_SIZE=$(du -h "$SUB_DIR/supplementary.zip" | cut -f1)
echo "  outputs/submission/supplementary.zip: $ZIP_SIZE"

echo
echo "=== submission bundle (outputs/submission/) ==="
ls -la "$SUB_DIR" | tail -5
echo
echo "Ready to upload to TBioCAS portal:"
echo "  - $SUB_DIR/manuscript.pdf"
echo "  - $SUB_DIR/cover_letter.md"
echo "  - $SUB_DIR/supplementary.zip"
