#!/usr/bin/env python3
"""ADR 0069 S7b — regenerate the normalization parity golden.

Runs the exact `lma_dataset.py::decode_lma_signal` normalization math for the
250 Hz case (channel-select is identity when channels are already the 21 target
order; resample is skipped at 250 Hz) on a DETERMINISTIC integer µV input, and
writes the int32 Q31 golden that `tests/normalize_parity.rs` checks the Rust
port (`src/normalize.rs`) against.

The input is generated by an integer formula reproduced bit-for-bit on the Rust
side, so only the golden output is committed. Regenerate (and bump the scipy
version note) if the filter operating point or the pipeline changes.

    python3 tools/dump_normalize_golden.py
"""
import json
import struct
from pathlib import Path

import numpy as np
import scipy
from scipy.signal import butter, sosfiltfilt

N_CH = 21
T = 128
SAMPLE_RATE = 250.0  # skips resample (|sr-250| <= 0.5)

OUT_DIR = Path(__file__).resolve().parents[1] / "lamquant-lossless" / "tests" / "fixtures" / "normalize"


def make_input() -> np.ndarray:
    """Deterministic integer µV signal — MUST match the Rust `synth_input`."""
    x = np.empty((N_CH, T), dtype=np.float32)
    for c in range(N_CH):
        for t in range(T):
            x[c, t] = float(((c * 37 + t * 5) % 4001) - 2000)
    return x


def normalize_250hz(data_f32: np.ndarray) -> np.ndarray:
    """The `decode_lma_signal` tail for the 250 Hz case: 0.5 Hz zero-phase HP → Q31."""
    sos = butter(2, 0.5, btype="high", fs=SAMPLE_RATE, output="sos")
    data = sosfiltfilt(sos, data_f32, axis=1)
    max_abs = float(np.max(np.abs(data)))
    assert max_abs >= 1e-12, "flat input"
    gain = 0.72 / max_abs
    return (data * gain * 2147483647.0).astype(np.int32)


def main() -> None:
    x = make_input()
    q31 = normalize_250hz(x)
    assert q31.shape == (N_CH, T) and q31.dtype == np.int32

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # raw int32 little-endian, row-major [N_CH, T]
    (OUT_DIR / "eeg_250hz_hp_q31.i32").write_bytes(
        struct.pack(f"<{q31.size}i", *q31.flatten(order="C").tolist())
    )
    (OUT_DIR / "eeg_250hz_hp_q31.manifest.json").write_text(
        json.dumps(
            {
                "adr": "0069-S7b",
                "n_ch": N_CH,
                "t": T,
                "sample_rate": SAMPLE_RATE,
                "pipeline": "channel-select(identity) -> sosfiltfilt(butter(2,0.5,fs=250,high)) -> q31",
                "input_formula": "x[c][t] = ((c*37 + t*5) %% 4001) - 2000  (float, µV)",
                "layout": "raw int32 LE, row-major [n_ch, t]",
                "scipy_version": scipy.__version__,
                "numpy_version": np.__version__,
                "note": "Rust f64 port vs scipy f64 (f32 input upcast losslessly); tolerance in the gate.",
            },
            indent=2,
        )
        + "\n"
    )
    print(f"wrote golden [{N_CH},{T}] int32 (scipy {scipy.__version__}) to {OUT_DIR}")
    print(f"  range [{int(q31.min())}, {int(q31.max())}]")


if __name__ == "__main__":
    main()
